# Dockerfile - Node + ffmpeg
FROM node:18-bullseye

# Install ffmpeg
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --production

# copy app
COPY . .

# create uploads dir
RUN mkdir -p uploads

EXPOSE 3000
CMD ["node", "server.js"]